// Generated by IcedCoffeeScript 1.6.3-g
(function() {
  var Packet, util;



  util = require('../util');

  Packet = (function() {
    function Packet() {}

    Packet.prototype.frame_packet = function(tag, body) {
      var bufs;
      bufs = [new Buffer([0xc0 | tag]), util.encode_length(body.length), body];
      return Buffer.concat(bufs);
    };

    return Packet;

  })();

  exports.Packet = Packet;

}).call(this);
