// Generated by IcedCoffeeScript 1.6.3-g
(function() {
  var C, RSA;



  C = require('./const').openpgp.public_key_algorithms;

  RSA = require('./rsa').RSA;

  exports.get_class = function(n) {
    switch (n) {
      case C.RSA:
      case C.RSA_ENCRYPT_ONLY:
      case C.RSA_SIGN_ONLY:
        return RSA;
      case ELGAMAL:
        throw new Error("no support yet for ElGamal");
        break;
      case DSA:
        throw new Error("no support yet for DSA");
        break;
      default:
        throw new Error("unknown public key system: " + n);
    }
  };

}).call(this);
