// Generated by IcedCoffeeScript 1.7.1-a
(function() {
  var ASP, C, K, Pair, Pub, bn, bufeq_secure, iced, konst, make_esc, __iced_k, __iced_k_noop, _ref;

  iced = require('iced-coffee-script/lib/coffee-script/iced').runtime;
  __iced_k = __iced_k_noop = function() {};

  bn = require('./bn');

  _ref = require('./util'), bufeq_secure = _ref.bufeq_secure, ASP = _ref.ASP;

  make_esc = require('iced-error').make_esc;

  konst = require('./const');

  C = konst.openpgp;

  K = konst.kb;

  Pub = (function() {
    Pub.type = C.public_key_algorithms.DSA;

    Pub.prototype.type = Pub.type;

    Pub.ORDER = ['p', 'q', 'g', 'y'];

    Pub.prototype.ORDER = Pub.ORDER;

    function Pub(_arg) {
      this.p = _arg.p, this.q = _arg.q, this.g = _arg.g, this.y = _arg.y;
    }

    Pub.prototype.serialize = function() {
      var e;
      return Buffer.concat((function() {
        var _i, _len, _ref1, _results;
        _ref1 = this.ORDER;
        _results = [];
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          e = _ref1[_i];
          _results.push(this[e].to_mpi_buffer());
        }
        return _results;
      }).call(this));
    };

    Pub.alloc = function(raw) {
      var d, err, o, orig_len, _i, _len, _ref1, _ref2;
      orig_len = raw.length;
      d = {};
      err = null;
      _ref1 = Pub.ORDER;
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        o = _ref1[_i];
        if (err == null) {
          _ref2 = bn.mpi_from_buffer(raw), err = _ref2[0], d[o] = _ref2[1], raw = _ref2[2];
        }
      }
      if (err) {
        return [err, null];
      } else {
        return [null, new Pub(d), orig_len - raw.length];
      }
    };

    Pub.prototype.verify = function(_arg, h, cb) {
      var err, hi, r, s, u1, u2, v, w;
      r = _arg[0], s = _arg[1];
      err = null;
      hi = bn.bn_from_left_n_bits(h, this.q.bitLength());
      w = s.modInverse(this.q);
      u1 = hi.multiply(w).mod(this.q);
      u2 = r.multiply(w).mod(this.q);
      v = this.g.modPow(u1, this.p).multiply(this.y.modPow(u2, this.p)).mod(this.p).mod(this.q);
      if (!v.equals(r)) {
        err = new Error("hash mismatch");
      }
      return cb(err);
    };

    return Pub;

  })();

  Pair = (function() {
    Pair.type = C.public_key_algorithms.DSA;

    Pair.prototype.type = Pair.type;

    function Pair(_arg) {
      this.pub = _arg.pub, this.priv = _arg.priv;
    }

    Pair.parse = function(pub_raw) {
      var err, key, len, _ref1;
      _ref1 = Pub.alloc(pub_raw), err = _ref1[0], key = _ref1[1], len = _ref1[2];
      if (key != null) {
        key = new Pair({
          pub: key
        });
      }
      return [err, key, len];
    };

    Pair.prototype.serialize = function() {
      return this.pub.serialize();
    };

    Pair.prototype.verify_unpad_and_check_hash = function(sig, data, hasher, cb) {
      var err, hash, v, ___iced_passed_deferral, __iced_deferrals, __iced_k, _ref1;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      err = null;
      if (Buffer.isBuffer(sig)) {
        _ref1 = Pair.read_sig_from_buf(sig), err = _ref1[0], sig = _ref1[1];
      }
      hash = hasher(data);
      (function(_this) {
        return (function(__iced_k) {
          if (sig.length !== 2) {
            return __iced_k(err = new Error("Expected 2 Bigints in the signature"));
          } else {
            (function(__iced_k) {
              __iced_deferrals = new iced.Deferrals(__iced_k, {
                parent: ___iced_passed_deferral,
                filename: "/Users/max/src/keybase/kbpgp/src/dsa.iced",
                funcname: "Pair.verify_unpad_and_check_hash"
              });
              _this.pub.verify(sig, hash, __iced_deferrals.defer({
                assign_fn: (function() {
                  return function() {
                    err = arguments[0];
                    return v = arguments[1];
                  };
                })(),
                lineno: 85
              }));
              __iced_deferrals._fulfill();
            })(__iced_k);
          }
        });
      })(this)((function(_this) {
        return function() {
          return cb(err);
        };
      })(this));
    };

    Pair.parse_sig = function(slice) {
      var buf, err, n, ret, _ref1;
      buf = slice.peek_rest_to_buffer();
      _ref1 = this.read_sig_from_buf(buf), err = _ref1[0], ret = _ref1[1], n = _ref1[2];
      if (err != null) {
        throw err;
      }
      slice.advance(n);
      return ret;
    };

    Pair.read_sig_from_buf = function(buf) {
      var err, n, o, order, orig_len, ret, x;
      orig_len = buf.length;
      order = ['r', 's'];
      err = null;
      ret = (function() {
        var _i, _len, _ref1, _results;
        _results = [];
        for (_i = 0, _len = order.length; _i < _len; _i++) {
          o = order[_i];
          if (!(err == null)) {
            continue;
          }
          _ref1 = bn.mpi_from_buffer(buf), err = _ref1[0], x = _ref1[1], buf = _ref1[2];
          _results.push(x);
        }
        return _results;
      })();
      n = orig_len - buf.length;
      return [err, ret, n];
    };

    return Pair;

  })();

  exports.DSA = exports.Pair = Pair;

}).call(this);
