// Generated by IcedCoffeeScript 1.6.3-g
(function() {
  var C, KeyWrapper, Lifespan, Primary, Subkey, UserId,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };



  C = require('./const');

  Lifespan = (function() {
    function Lifespan(_arg) {
      this.generated = _arg.generated, this.expire_in = _arg.expire_in;
      this.expire_in || (this.expire_in = C.default_key_expire_in);
    }

    return Lifespan;

  })();

  KeyWrapper = (function() {
    function KeyWrapper(_arg) {
      this.key = _arg.key, this.lifespan = _arg.lifespan, this._pgp = _arg._pgp, this._keybase = _arg._keybase, this.flags = _arg.flags;
    }

    KeyWrapper.prototype.kid = function() {
      return this.key.kid();
    };

    KeyWrapper.prototype.ekid = function() {
      return this.key.ekid();
    };

    return KeyWrapper;

  })();

  Subkey = (function(_super) {
    __extends(Subkey, _super);

    function Subkey(_arg) {
      var flags, key, lifespan, _keybase, _pgp;
      key = _arg.key, flags = _arg.flags, _pgp = _arg._pgp, _keybase = _arg._keybase, this.desc = _arg.desc, lifespan = _arg.lifespan, this.primary = _arg.primary;
      Subkey.__super__.constructor.call(this, {
        key: key,
        lifespan: lifespan,
        flags: flags,
        _pgp: _pgp,
        _keybase: _keybase
      });
    }

    return Subkey;

  })(KeyWrapper);

  Primary = (function(_super) {
    __extends(Primary, _super);

    function Primary(_arg) {
      var flags, key, lifespan, _keybase, _pgp;
      key = _arg.key, lifespan = _arg.lifespan, flags = _arg.flags, _pgp = _arg._pgp, _keybase = _arg._keybase;
      Primary.__super__.constructor.call(this, {
        key: key,
        lifespan: lifespan,
        flags: flags,
        _pgp: _pgp,
        _keybase: _keybase
      });
    }

    return Primary;

  })(KeyWrapper);

  UserId = (function() {
    function UserId(_arg) {
      this.openpgp = _arg.openpgp, this.components = _arg.components;
      if (this.components == null) {
        this._parse();
      }
    }

    UserId.prototype.get_openpgp = function() {
      return this.openpgp;
    };

    UserId.prototype._parse = function() {
      var m, s, x;
      x = /^([^(<]*?)\s+(\((.*?)\)\s+)?<(.*)?>$/;
      s = Buffer.isBuffer(this.openpgp) ? this.openpgp.toString('utf8') : this.openpgp;
      if ((m = s.match(x)) != null) {
        return this.components = {
          username: m[1],
          comment: m[3],
          email: m[4]
        };
      }
    };

    UserId.make = function(components) {
      var c, comment, openpgp;
      comment = (c = components.comment) != null ? "(" + c + ") " : "";
      openpgp = "" + components.username + " " + comment + "<" + components.email + ">";
      return new UserId({
        openpgp: openpgp,
        components: components
      });
    };

    return UserId;

  })();

  exports.Lifespan = Lifespan;

  exports.Subkey = Subkey;

  exports.Primary = Primary;

  exports.UserId = UserId;

}).call(this);
