// Generated by IcedCoffeeScript 1.6.3-g
(function() {
  var generate, generate_prime, openpgp, prng;



  openpgp = require('openpgp');

  prng = require('triplesec').prng;

  generate = function(n_bits, cb) {};

  generate_prime = function(n_bits, p, cb) {};

  exports.generate = generate;

  exports.generate_prime = generate_prime;

}).call(this);
