// Generated by IcedCoffeeScript 1.6.3-g
(function() {
  var AES, C, CAST5, triplesec;



  C = require('./const').openpgp.symmetric_key_algorithms;

  triplesec = require('triplesec');

  AES = triplesec.ciphers.AES;

  CAST5 = require('./openpgp/cast5').CAST5;

  exports.get_cipher = function(n) {
    switch (n) {
      case C.AES128:
        return {
          klass: AES,
          key_size: 16
        };
      case C.AES192:
        return {
          klass: AES,
          key_size: 24
        };
      case C.AES256:
        return {
          klass: AES,
          key_size: 32
        };
      case C.CAST5:
        return {
          klass: CAST5,
          key_size: CAST5.keySize
        };
      default:
        throw new Error("unknown cipher: " + n);
    }
  };

}).call(this);
