// Generated by IcedCoffeeScript 1.7.1-c
(function() {
  var Base, Chain, InBlocker, ReverseAdapter, SimpleInit, StreamAdapter, assert, iced, make_esc, stream, __iced_k, __iced_k_noop,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  iced = require('iced-runtime').iced;
  __iced_k = __iced_k_noop = function() {};

  stream = require('stream');

  make_esc = require('iced-error').make_esc;

  assert = require('assert');

  Base = (function() {
    function Base() {}

    Base.prototype.chunk = function(_arg, cb) {
      var data, eof;
      data = _arg.data, eof = _arg.eof;
      return cb(new Error("unimplemented!"));
    };

    return Base;

  })();

  Chain = (function(_super) {
    __extends(Chain, _super);

    function Chain() {
      this.links = [];
    }

    Chain.prototype.push_xbt = function(link) {
      return this.links.push(link);
    };

    Chain.prototype.chunk = function(_arg, cb) {
      var data, eof, esc, l, out, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      data = _arg.data, eof = _arg.eof;
      esc = make_esc(cb, "Chain::chunk");
      out = null;
      (function(_this) {
        return (function(__iced_k) {
          var _i, _len, _ref, _results, _while;
          _ref = _this.links;
          _len = _ref.length;
          _i = 0;
          _results = [];
          _while = function(__iced_k) {
            var _break, _continue, _next;
            _break = function() {
              return __iced_k(_results);
            };
            _continue = function() {
              return iced.trampoline(function() {
                ++_i;
                return _while(__iced_k);
              });
            };
            _next = function(__iced_next_arg) {
              _results.push(__iced_next_arg);
              return _continue();
            };
            if (!(_i < _len)) {
              return _break();
            } else {
              l = _ref[_i];
              (function(__iced_k) {
                __iced_deferrals = new iced.Deferrals(__iced_k, {
                  parent: ___iced_passed_deferral,
                  filename: "/Users/max/src/keybase/kbpgp/src/xbt.iced",
                  funcname: "Chain.chunk"
                });
                l.chunk({
                  data: data,
                  eof: eof
                }, esc(__iced_deferrals.defer({
                  assign_fn: (function() {
                    return function() {
                      return data = arguments[0];
                    };
                  })(),
                  lineno: 38
                })));
                __iced_deferrals._fulfill();
              })(function() {
                return _next(out = data);
              });
            }
          };
          _while(__iced_k);
        });
      })(this)((function(_this) {
        return function() {
          return cb(null, out);
        };
      })(this));
    };

    return Chain;

  })(Base);

  SimpleInit = (function(_super) {
    __extends(SimpleInit, _super);

    function SimpleInit() {
      this._did_init = false;
    }

    SimpleInit.prototype.init = function(cb) {
      var data, err, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      err = data = null;
      (function(_this) {
        return (function(__iced_k) {
          if (!_this._did_init) {
            _this._did_init = true;
            (function(__iced_k) {
              __iced_deferrals = new iced.Deferrals(__iced_k, {
                parent: ___iced_passed_deferral,
                filename: "/Users/max/src/keybase/kbpgp/src/xbt.iced",
                funcname: "SimpleInit.init"
              });
              _this._v_init(__iced_deferrals.defer({
                assign_fn: (function() {
                  return function() {
                    err = arguments[0];
                    return data = arguments[1];
                  };
                })(),
                lineno: 53
              }));
              __iced_deferrals._fulfill();
            })(__iced_k);
          } else {
            return __iced_k();
          }
        });
      })(this)((function(_this) {
        return function() {
          return cb(err, data);
        };
      })(this));
    };

    SimpleInit.prototype.chunk = function(_arg, cb) {
      var data, eof, esc, init_data, out, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      data = _arg.data, eof = _arg.eof;
      esc = make_esc(cb, "SimpleInit::chunk");
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/max/src/keybase/kbpgp/src/xbt.iced",
            funcname: "SimpleInit.chunk"
          });
          _this.init(esc(__iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                return init_data = arguments[0];
              };
            })(),
            lineno: 58
          })));
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          (function(__iced_k) {
            __iced_deferrals = new iced.Deferrals(__iced_k, {
              parent: ___iced_passed_deferral,
              filename: "/Users/max/src/keybase/kbpgp/src/xbt.iced",
              funcname: "SimpleInit.chunk"
            });
            _this._v_chunk({
              data: data,
              eof: eof
            }, esc(__iced_deferrals.defer({
              assign_fn: (function() {
                return function() {
                  return out = arguments[0];
                };
              })(),
              lineno: 59
            })));
            __iced_deferrals._fulfill();
          })(function() {
            if (typeof init_data !== "undefined" && init_data !== null) {
              out = Buffer.concat([init_data, out]);
            }
            return cb(null, out);
          });
        };
      })(this));
    };

    return SimpleInit;

  })(Base);

  InBlocker = (function(_super) {
    __extends(InBlocker, _super);

    function InBlocker(block_size) {
      this.block_size = block_size;
      InBlocker.__super__.constructor.call(this);
      this._buffers = [];
      this._dlen = 0;
      this._p = 0;
      this._input_len = 0;
    }

    InBlocker.prototype._push_data = function(b) {
      if (b != null ? b.length : void 0) {
        this._buffers.push(b);
        return this._dlen += b.length;
      }
    };

    InBlocker.prototype._pop_block = function(block_size) {
      var b, end, getbuf, i, leftover, out, slices, start, stuff, total, _i, _len, _ref;
      total = 0;
      slices = [];
      block_size || (block_size = this.block_size);
      getbuf = function(buf, start, end) {
        if (!start && (end == null)) {
          return buf;
        } else if (end == null) {
          return buf.slice(start);
        } else {
          return buf.slice(start, end);
        }
      };
      _ref = this._buffers;
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        b = _ref[i];
        start = i === 0 ? this._p : 0;
        stuff = b.length - start;
        leftover = total + stuff - block_size;
        if (leftover < 0) {
          slices.push(getbuf(b, start));
          total += stuff;
        } else if (leftover === 0) {
          slices.push(getbuf(b, start));
          total += stuff;
          this._buffers = this._buffers.slice(i + 1);
          this._p = 0;
          break;
        } else {
          end = b.length - leftover;
          slices.push(getbuf(b, start, end));
          this._buffers = this._buffers.slice(i);
          this._p = end;
          break;
        }
      }
      out = Buffer.concat(slices);
      assert(out.length === block_size);
      return out;
    };

    InBlocker.prototype._v_chunk = function(_arg, cb) {
      var data, eof, err, out, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      data = _arg.data, eof = _arg.eof;
      if (data != null) {
        this._input_len += data.length;
      }
      this._push_data(data);
      err = out = null;
      (function(_this) {
        return (function(__iced_k) {
          if (eof) {
            (function(__iced_k) {
              __iced_deferrals = new iced.Deferrals(__iced_k, {
                parent: ___iced_passed_deferral,
                filename: "/Users/max/src/keybase/kbpgp/src/xbt.iced",
                funcname: "InBlocker._v_chunk"
              });
              _this._handle_eof(__iced_deferrals.defer({
                assign_fn: (function() {
                  return function() {
                    err = arguments[0];
                    return out = arguments[1];
                  };
                })(),
                lineno: 125
              }));
              __iced_deferrals._fulfill();
            })(__iced_k);
          } else {
            (function(__iced_k) {
              if (_this._dlen >= _this.block_size) {
                (function(__iced_k) {
                  __iced_deferrals = new iced.Deferrals(__iced_k, {
                    parent: ___iced_passed_deferral,
                    filename: "/Users/max/src/keybase/kbpgp/src/xbt.iced",
                    funcname: "InBlocker._v_chunk"
                  });
                  _this._handle_block(__iced_deferrals.defer({
                    assign_fn: (function() {
                      return function() {
                        err = arguments[0];
                        return out = arguments[1];
                      };
                    })(),
                    lineno: 127
                  }));
                  __iced_deferrals._fulfill();
                })(__iced_k);
              } else {
                return __iced_k();
              }
            })(__iced_k);
          }
        });
      })(this)((function(_this) {
        return function() {
          return cb(err, out);
        };
      })(this));
    };

    InBlocker.prototype._handle_eof = function(cb) {
      var buf, bufs, data, end, eof, esc, i, out, outbufs, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      esc = make_esc(cb, "InBlocker::_v_chunk");
      i = 0;
      outbufs = [];
      bufs = [];
      if (this._buffers.length && this._p > 0) {
        bufs.push(this._buffers.shift().slice(this._p));
      }
      bufs = bufs.concat(this._buffers);
      buf = Buffer.concat(bufs);
      this._buffers = [];
      this._dlen = 0;
      this._p = 0;
      eof = false;
      (function(_this) {
        return (function(__iced_k) {
          var _results, _while;
          _results = [];
          _while = function(__iced_k) {
            var _break, _continue, _next;
            _break = function() {
              return __iced_k(_results);
            };
            _continue = function() {
              return iced.trampoline(function() {
                return _while(__iced_k);
              });
            };
            _next = function(__iced_next_arg) {
              _results.push(__iced_next_arg);
              return _continue();
            };
            if (!!eof) {
              return _break();
            } else {
              end = i + _this.block_size;
              eof = end >= buf.length;
              data = buf.slice(i, end);
              (function(__iced_k) {
                __iced_deferrals = new iced.Deferrals(__iced_k, {
                  parent: ___iced_passed_deferral,
                  filename: "/Users/max/src/keybase/kbpgp/src/xbt.iced",
                  funcname: "InBlocker._handle_eof"
                });
                _this._v_inblock_chunk({
                  data: data,
                  eof: eof
                }, esc(__iced_deferrals.defer({
                  assign_fn: (function() {
                    return function() {
                      return out = arguments[0];
                    };
                  })(),
                  lineno: 157
                })));
                __iced_deferrals._fulfill();
              })(function() {
                outbufs.push(out);
                return _next(i = end);
              });
            }
          };
          _while(__iced_k);
        });
      })(this)((function(_this) {
        return function() {
          out = Buffer.concat(outbufs);
          return cb(null, out);
        };
      })(this));
    };

    InBlocker.prototype._handle_block = function(cb) {
      var data, err, out, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      data = this._pop_block();
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/max/src/keybase/kbpgp/src/xbt.iced",
            funcname: "InBlocker._handle_block"
          });
          _this._v_inblock_chunk({
            data: data,
            eof: false
          }, __iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                err = arguments[0];
                return out = arguments[1];
              };
            })(),
            lineno: 168
          }));
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          return cb(err, out);
        };
      })(this));
    };

    return InBlocker;

  })(SimpleInit);

  StreamAdapter = (function(_super) {
    __extends(StreamAdapter, _super);

    function StreamAdapter(_arg) {
      this.xbt = _arg.xbt;
      StreamAdapter.__super__.constructor.call(this);
    }

    StreamAdapter.prototype._transform = function(data, encoding, cb) {
      var err, out, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      if (typeof endcoding !== "undefined" && endcoding !== null) {
        data = new Buffer(data, encoding);
      }
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/max/src/keybase/kbpgp/src/xbt.iced",
            funcname: "StreamAdapter._transform"
          });
          _this.xbt.chunk({
            eof: false,
            data: data
          }, __iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                err = arguments[0];
                return out = arguments[1];
              };
            })(),
            lineno: 180
          }));
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          if (!(typeof err !== "undefined" && err !== null) && (typeof out !== "undefined" && out !== null)) {
            _this.push(out);
          }
          return cb(err);
        };
      })(this));
    };

    StreamAdapter.prototype._flush = function(cb) {
      var err, out, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/max/src/keybase/kbpgp/src/xbt.iced",
            funcname: "StreamAdapter._flush"
          });
          _this.xbt.chunk({
            eof: true
          }, __iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                err = arguments[0];
                return out = arguments[1];
              };
            })(),
            lineno: 185
          }));
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          if (!(typeof err !== "undefined" && err !== null) && (typeof out !== "undefined" && out !== null)) {
            _this.push(out);
          }
          return cb(err);
        };
      })(this));
    };

    return StreamAdapter;

  })(stream.Transform);

  ReverseAdapter = (function(_super) {
    __extends(ReverseAdapter, _super);

    function ReverseAdapter(_arg) {
      var hiwat;
      this.stream = _arg.stream, hiwat = _arg.hiwat;
      ReverseAdapter.__super__.constructor.call(this);
      this._buffers = [];
      this._dlen = 0;
      this._hiwat = hiwat || 0x10000;
    }

    ReverseAdapter.prototype._push_data = function(data) {
      if ((data != null) && data.length) {
        this._buffers.push(data);
        this._dlen += data.length;
        return true;
      } else {
        return false;
      }
    };

    ReverseAdapter.prototype._transform = function(data, cb) {
      var diff, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/max/src/keybase/kbpgp/src/xbt.iced",
            funcname: "ReverseAdapter._transform"
          });
          _this.stream.write(data, __iced_deferrals.defer({
            lineno: 209
          }));
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          while ((diff = _this._hiwat - _this._dlen) > 0) {
            if (!_this._push_data(_this.stream.read(diff))) {
              break;
            }
          }
          return cb();
        };
      })(this));
    };

    ReverseAdapter.prototype._flush = function(cb) {
      this.stream.end();
      this.stream.on('data', (function(_this) {
        return function(data) {
          return _this._push_data(data);
        };
      })(this));
      this.stream.once('error', function(err) {
        return cb(err);
      });
      return this.stream.once('end', function(data) {
        return cb(null);
      });
    };

    ReverseAdapter.prototype._consume_bufs = function() {
      var out;
      out = Buffer.concat(this._buffers);
      this._buffers = [];
      this._dlen = 0;
      return out;
    };

    ReverseAdapter.prototype.chunk = function(_arg, cb) {
      var data, eof, esc, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      data = _arg.data, eof = _arg.eof;
      esc = make_esc(cb, "ReverseAdapter::chunk");
      (function(_this) {
        return (function(__iced_k) {
          if (data != null) {
            (function(__iced_k) {
              __iced_deferrals = new iced.Deferrals(__iced_k, {
                parent: ___iced_passed_deferral,
                filename: "/Users/max/src/keybase/kbpgp/src/xbt.iced",
                funcname: "ReverseAdapter.chunk"
              });
              _this._transform(data, esc(__iced_deferrals.defer({
                lineno: 228
              })));
              __iced_deferrals._fulfill();
            })(__iced_k);
          } else {
            return __iced_k();
          }
        });
      })(this)((function(_this) {
        return function() {
          (function(__iced_k) {
            if (eof) {
              (function(__iced_k) {
                __iced_deferrals = new iced.Deferrals(__iced_k, {
                  parent: ___iced_passed_deferral,
                  filename: "/Users/max/src/keybase/kbpgp/src/xbt.iced",
                  funcname: "ReverseAdapter.chunk"
                });
                _this._flush(esc(__iced_deferrals.defer({
                  lineno: 229
                })));
                __iced_deferrals._fulfill();
              })(__iced_k);
            } else {
              return __iced_k();
            }
          })(function() {
            return cb(null, _this._consume_bufs());
          });
        };
      })(this));
    };

    return ReverseAdapter;

  })(Base);

  exports.Base = Base;

  exports.Chain = Chain;

  exports.SimpleInit = SimpleInit;

  exports.StreamAdapter = StreamAdapter;

  exports.ReverseAdapter = ReverseAdapter;

  exports.InBlocker = InBlocker;

}).call(this);
