
mods =
  aead : require '../files/aead.iced'
  brainpool256 : require '../files/brainpool256.iced'
  brainpool384: require '../files/brainpool384.iced'
  brainpool512: require '../files/brainpool512.iced'
  burner: require '../files/burner.iced'
  cv25519: require '../files/cv25519.iced'
  eddsa : require '../files/eddsa.iced'
  box : require '../files/box.iced'
  kbbox : require '../files/kbbox.iced'
  fp : require '../files/fp.iced'
  nacl1 : require '../files/nacl1.iced'
  nacl2 : require '../files/nacl2.iced'
  nacl_export : require '../files/nacl_export.iced'
  ecc3 : require '../files/ecc3.iced'
  errors : require '../files/errors.iced'
  verify_sigs : require '../files/verify_sigs.iced'
  sigeng : require '../files/sigeng.iced'
  revoked_subkeys : require '../files/revoked_subkey.iced'
  multiples : require "../files/multiples.iced"
  unbox_cant_verify : require '../files/unbox_cant_verify.iced'
  zip : require '../files/zip.iced'
  ecc1 : require '../files/ecc1.iced'
  ecc2 : require '../files/ecc2.iced'
  rfc3394 : require '../files/rfc3394.iced'
  google_end_to_end : require '../files/google_end_to_end.iced'
  verify_detached_sigs : require '../files/verify_detached_sigs.iced'
  hide : require '../files/hide.iced'
  critical_subpacket : require '../files/critical_subpacket.iced'
  secret_subkeys : require '../files/secret_subkeys.iced'
  secret_subkeys_incomplete : require '../files/secret_subkeys_incomplete.iced'
  sig_various_hashes : require '../files/sig_various_hashes.iced'
  openpgp_js_cure53_audit : require '../files/openpgp_js_cure53_audit.iced'
  bzip2 : require '../files/bzip2.iced'
  decode_pgp : require '../files/decode_pgp.iced'
  get_primary_uid : require '../files/get_primary_uid.iced'
  sig_v3 : require '../files/sig_v3.iced'
  sig_gocli : require '../files/sig_gocli.iced'
  elgamal : require '../files/elgamal.iced'
  elgamal_v3 : require '../files/elgamal_v3.iced'
  dsa : require '../files/dsa.iced'
  rsa_8192 : require '../files/rsa_8192.iced'
  buffer_shfit_right : require '../files/buffer_shift_right.iced'
  verify_clearsign_sigs : require '../files/verify_clearsign_sigs.iced'
  decoder : require '../files/decoder.iced'
  userid : require '../files/userid.iced'
  msg_roundtrip : require '../files/msg_roundtrip.iced'
  decrypt_verify_msg : require '../files/decrypt_verify_msg.iced'
  keymanager : require '../files/keymanager.iced'
  cast5 : require '../files/cast5.iced'
  basex : require '../files/basex.iced'
  cfb : require '../files/cfb.iced'
  fermat2 : require '../files/fermat2.iced'
  miller_rabin : require '../files/miller_rabin.iced'
  rsa : require '../files/rsa.iced'
  keyfetcher : require '../files/keyfetcher.iced'
  revokes : require '../files/revokes.iced'
  p3skb : require '../files/p3skb.iced'
  p3skb_r : require '../files/p3skb_r.iced'
  p521 : require '../files/p521.iced'
  padding_oracle : require '../files/padding_oracle.iced'
  problem_sigs : require '../files/problem_sigs.iced'
  gh_issue_73 : require '../files/gh_issue_73.iced'
  key_expirations : require '../files/key_expirations.iced'
  subkey_expiration : require '../files/subkey_expiration.iced'
  subkey_multiple_sigs : require '../files/subkey_multiple_sigs.iced'
  subkey_no_cross_sig : require '../files/subkey_no_cross_sig.iced'
  subkey_preference : require '../files/subkey_preference.iced'
  subpacket33 : require '../files/subpacket33.iced'
  ukm : require '../files/ukm.iced'
  merge_pgp_public : require '../files/merge_pgp_public.iced'

v = Object.keys(mods)
v.sort()
for k in v
  console.log k

{BrowserRunner} = require('iced-test')

window.onload = () ->
  br = new BrowserRunner { log : "log", rc : "rc" }
  await br.run mods, defer rc
