// Generated by IcedCoffeeScript 1.7.1-c
(function() {
  var BaseKey, BaseKeyPair, K, NaclDh, Pair, SRF, TYPE, b2u, box, bufeq_fast, konst, u2b, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  box = require('tweetnacl').box;

  SRF = require('../rand').SRF;

  konst = require('../const');

  K = konst.kb;

  bufeq_fast = require('../util').bufeq_fast;

  _ref = require('../basekeypair'), BaseKey = _ref.BaseKey, BaseKeyPair = _ref.BaseKeyPair;

  NaclDh = require('./dh').Pair;

  TYPE = K.public_key_algorithms.NACL_EDDSA;

  b2u = function(b) {
    return new Uint8Array(b);
  };

  u2b = function(u) {
    return new Buffer(u);
  };

  Pair = (function(_super) {
    __extends(Pair, _super);

    function Pair() {
      return Pair.__super__.constructor.apply(this, arguments);
    }

    Pair.prototype.construct = function(_arg) {
      var priv, pub;
      pub = _arg.pub, priv = _arg.priv;
      return Pair.__super__.construct.call(this, {
        pub: pub,
        priv: priv
      });
    };

    return Pair;

  })(BaseKeyPair);

  exports.DH = exports.Pair = Pair;

}).call(this);
