// Generated by IcedCoffeeScript 1.7.1-c
(function() {
  var K, Packet, pack, util;

  util = require('../../util');

  pack = require('../encode').pack;

  K = require('../../const').kb;

  Packet = (function() {
    function Packet() {}

    Packet.prototype.frame_packet = function(tag, body) {
      return {
        tag: tag,
        body: body
      };
    };

    Packet.alloc = function(tag, body) {
      var P3SKB;
      switch (tag) {
        case K.packet_tags.p3skb:
          P3SKB = require('./p3skb').P3SKB;
          return P3SKB.alloc({
            tag: tag,
            body: body
          });
        default:
          return [new Error("unknown packet tag: " + tag), null];
      }
    };

    return Packet;

  })();

  exports.Packet = Packet;

}).call(this);
