// Generated by IcedCoffeeScript 1.7.1-c
(function() {
  var K, Packet, UserID,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  K = require('../../const').kb;

  Packet = require('./base').Packet;

  UserID = (function(_super) {
    __extends(UserID, _super);

    function UserID(uid) {
      this.uid = uid;
      UserID.__super__.constructor.call(this);
    }

    UserID.prototype.to_json = function() {
      return {
        userid: this.uid
      };
    };

    UserID.prototype.write = function() {
      return this.frame_packet(K.packet_tags.userid, this.to_json());
    };

    return UserID;

  })(Packet);

}).call(this);
